### ISSUE TITLE
哪个端口被占用了呢？

### ISSUE THREAD

**Issue by luckypoem** [mitnk/lightsocks#1]
hi.
root@AR:~/lightsocks# ls
config.py   encrypt.py	 local.py   server.erl
config.pyc  encrypt.pyc  README.md  server.py
root@AR:~/lightsocks# python server.py
Traceback (most recent call last):
  File "server.py", line 50, in <module>
    server = ThreadedTCPServer((SERVER_IP, SERVER_PORT), LightHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@AR:~/lightsocks#

**Comment by mitnk** [comment]
Hello,

Since ThreadedTCPServer has `allow_reuse_address` set to `True`, so it should not be the case itself occupied the port. So I guess there was other program using the port.

you can use `sudo lsof -nPi | grep -i listen` next time to check which app is using it.

This project is only a toy or POC. shouldn't be used on prod. :)

**Comment by luckypoem** [comment]
hi.

"you can use sudo lsof -nPi | grep -i listen next time to check which app is using it.",你没有说查哪个端口啊？是8192？我查了一下，无程序占用该端口：
root@AR:~/lightsocks# lsof -i:8192
root@AR:~/lightsocks#

你可告知你这个程序／ThreadedTCPServer是默认使用哪个端口吗？
谢谢你！

**Comment by mitnk** [comment]
config.py 里有
端口是8388
